// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mapa-warianty/LeafletESRI.tsx": () => import("../components/mockups/mapa-warianty/LeafletESRI.tsx"),
  "./components/mockups/mapa-warianty/MapLibreGL.tsx": () => import("../components/mockups/mapa-warianty/MapLibreGL.tsx")
};
